### ISSUE TITLE
it shows that there is anviles there when ther isnt

### ISSUE THREAD

**Issue by Sakott** [aXe18/EnigmaSMP-Public#10]
![2023-02-10_15 07 16](https://user-images.githubusercontent.com/124718466/218101839-8fd80c50-07cb-418a-a9e3-d28c55774002.png)

**Comment by Damis1** [comment]
Also We have problem with Anvil remove it's not working u cannot remove anvil

**Comment by aXe18** [comment]
This should be fixed now. At least i could not do that anymore on any worlds
