### ISSUE TITLE
I was just walking

### ISSUE THREAD

**Issue by Sakott** [aXe18/EnigmaSMP-Public#16]
![2023-02-11_13 31 15](https://user-images.githubusercontent.com/124718466/218255709-711651bc-5ff8-439d-8795-cf30661bfd61.png)

**Comment by aXe18** [comment]
Placing sugarcane ? It takes money if you place same blocks over again and again

**Comment by aXe18** [comment]
Dont place same crops in same spot where you broke them, this is made for a reason to prevent "duping money"
